server:
  port: 8080

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

spring:
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    url: jdbc:h2:file:./data/demo
    data-username: sa
    driver-class-name: org.h2.Driver
#    data-password: test
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
   root: INFO
   qa.qdb.api.client.JphHttpClient: INFO
